export const LOGIN_API = "LOGIN_API";
export const LOGIN_API_SUCCEED = "LOGIN_API_SUCCEED";
export const LOGIN_API_FAIL = "LOGIN_API_FAIL";

export const UPDATE_REMEMBERED_PATH = "UPDATE_REMEMBERED_PATH";
export const CLOSE_MODAL_MESSAGE = "CLOSE_MODAL_MESSAGE";
export const OPEN_MODAL_MESSAGE = "OPEN_MODAL_MESSAGE";

export const REGISTER_API = "REGISTER_API";
export const REGISTER_API_SUCCEED = "REGISTER_API_SUCCEED";
export const REGISTER_API_FAIL = "REGISTER_API_FAIL";

export const FORGOTPASSWORD_API = "FORGOTPASSWORD_API";
export const FORGOTPASSWORD_API_SUCCEED = "FORGOTPASSWORD_API_SUCCEED";
export const FORGOTPASSWORD_API_FAIL = "FORGOTPASSWORD_API_FAIL";

export const CONFIRMPASSWORD_API = "CONFIRMPASSWORD_API";
export const CONFIRMPASSWORD_API_SUCCEED = "CONFIRMPASSWORD_API_SUCCEED";
export const CONFIRMPASSWORD_API_FAIL = "CONFIRMPASSWORD_API_FAIL";

export const CHANGEPASSWORD_API = "CHANGEPASSWORD_API";
export const CHANGEPASSWORD_API_SUCCEED = "CHANGEPASSWORD_API_SUCCEED";
export const CHANGEPASSWORD_API_FAIL = "CHANGEPASSWORD_API_FAIL";

export const RESETPASSWORD_API = "RESETPASSWORD_API";
export const RESETPASSWORD_API_SUCCEED = "RESETPASSWORD_API_SUCCEED";
export const RESETPASSWORD_API_FAIL = "RESETPASSWORD_API_FAIL";

export const GET_SCHEDULE_API = "GET_SCHEDULE_API";
export const GET_SCHEDULE_API_SUCCEED = "GET_SCHEDULE_API_SUCCEED";
export const GET_SCHEDULE_API_FAIL = "GET_SCHEDULE_API_FAIL";

export const ADD_SCHEDULE_API = "ADD_SCHEDULE_API";
export const ADD_SCHEDULE_API_SUCCEED = "ADD_SCHEDULE_API_SUCCEED";
export const ADD_SCHEDULE_API_FAIL = "ADD_SCHEDULE_API_FAIL";

export const GET_TUTORINFO_API = "GET_TUTORINFO_API";
export const GET_TUTORINFO_API_SUCCEED = "GET_TUTORINFO_API_SUCCEED";
export const GET_TUTORINFO_API_FAIL = "GET_TUTORINFO_API_FAIL";

export const GET_STUDENTINFO_API = "GET_STUDENTINFO_API";
export const GET_STUDENTINFO_API_SUCCEED = "GET_STUDENTINFO_API_SUCCEED";
export const GET_STUDENTINFO_API_FAIL = "GET_STUDENTINFO_API_FAIL";

export const GET_TEACHINGSCHEDULE_API = "GET_TEACHINGSCHEDULE_API";
export const GET_TEACHINGSCHEDULE_API_SUCCEED =
  "GET_TEACHINGSCHEDULE_API_SUCCEED";
export const GET_TEACHINGSCHEDULE_API_FAIL = "GET_TEACHINGSCHEDULE_API_FAIL";

export const GET_LEARNINGSCHEDULE_API = "GET_LEARNINGSCHEDULE_API";
export const GET_LEARNINGSCHEDULE_API_SUCCEED =
  "GET_LEARNINGSCHEDULE_API_SUCCEED";
export const GET_LEARNINGSCHEDULE_API_FAIL = "GET_LEARNINGSCHEDULE_API_FAIL";

export const UPDATE_TUTORINFO_API = "UPDATE_TUTORINFO_API";
export const UPDATE_TUTORINFO_API_SUCCEED = "UPDATE_TUTORINFO_API_SUCCEED";
export const UPDATE_TUTORINFO_API_FAIL = "UPDATE_TUTORINFO_API_FAIL";

export const UPDATE_STUDENTINFO_API = "UPDATE_STUDENTINFO_API";
export const UPDATE_STUDENTINFO_API_SUCCEED = "UPDATE_STUDENTINFO_API_SUCCEED";
export const UPDATE_STUDENTINFO_API_FAIL = "UPDATE_STUDENTINFO_API_FAIL";

export const GET_TUTORUSERS_API = "GET_TUTORUSERS_API";
export const GET_TUTORUSERS_API_SUCCEED = "GET_TUTORUSERS_API_SUCCEED";
export const GET_TUTORUSERS_API_FAIL = "GET_TUTORUSERS_API_FAIL";

export const GET_STUDENTUSERS_API = "GET_STUDENTUSERS_API";
export const GET_STUDENTUSERS_API_SUCCEED = "GET_STUDENTUSERS_API_SUCCEED";
export const GET_STUDENTUSERS_API_FAIL = "GET_STUDENTUSERS_API_FAIL";

export const STUDENT_REGISTER_SCHEDULE = "STUDENT_REGISTER_SCHEDULE";
export const STUDENT_REGISTER_SCHEDULE_SUCCEED =
  "STUDENT_REGISTER_SCHEDULE_SUCCEED";
export const STUDENT_REGISTER_SCHEDULE_FAIL = "STUDENT_REGISTER_SCHEDULE_FAIL";

export const GET_LIST_STUDENT_REGISTER = "GET_LIST_STUDENT_REGISTER";
export const GET_LIST_STUDENT_REGISTER_SUCCEED =
  "GET_LIST_STUDENT_REGISTER_SUCCEED";
export const GET_LIST_STUDENT_REGISTER_FAILED =
  "GET_LIST_STUDENT_REGISTER_FAILED";

export const TUTOR_ACCEPT = "TUTOR_ACCEPT";
export const TUTOR_ACCEPT_SUCCEED = "TUTOR_ACCEPT_SUCCEED";
export const TUTOR_ACCEPT_FAILED = "TUTOR_ACCEPT_FAILED";

export const LIST_ADMIN_NEED_ACCEPT = "LIST_ADMIN_NEED_ACCEPT";
export const LIST_ADMIN_NEED_ACCEPT_SUCCEED = "LIST_ADMIN_NEED_ACCEPT_SUCCEED";
export const LIST_ADMIN_NEED_ACCEPT_FAILED = "LIST_ADMIN_NEED_ACCEPT_FAILED";

export const ADMIN_ACCEPT = "ADMIN_ACCEPT";
export const ADMIN_ACCEPT_SUCCEED = "ADMIN_ACCEPT_SUCCEED";
export const ADMIN_ACCEPT_FAILED = "ADMIN_ACCEPT_FAILED";

export const GET_LIST_SCHEDULE_STUDENT_REGISTER =
  "GET_LIST_SCHEDULE_STUDENT_REGISTER";
export const GET_LIST_SCHEDULE_STUDENT_REGISTER_SUCCEED =
  "GET_LIST_SCHEDULE_STUDENT_REGISTER_SUCCEED";
export const GET_LIST_SCHEDULE_STUDENT_REGISTER_FAILED =
  "GET_LIST_SCHEDULE_STUDENT_REGISTER_FAILED";

export const STUDENT_REMOVE_SCHEDULE_REGISTER =
  "STUDENT_REMOVE_SCHEDULE_REGISTER";
export const STUDENT_REMOVE_SCHEDULE_REGISTER_SUCCEED =
  "STUDENT_REMOVE_SCHEDULE_REGISTER_SUCCEED";
export const STUDENT_REMOVE_SCHEDULE_REGISTER_FAILED =
  "STUDENT_REMOVE_SCHEDULE_REGISTER_FAILED";

export const ADMIN_DENIED = "ADMIN_DENIED";
export const ADMIN_DENIED_SUCCEED = "ADMIN_DENIED_SUCCEED";
export const ADMIN_DENIED_FAILED = "ADMIN_DENIED_FAILED";

export const REMOVE_TUTOR = "REMOVE_TUTOR";
export const REMOVE_TUTOR_SUCCEED = "REMOVE_TUTOR_SUCCEED";
export const REMOVE_TUTOR_FAILED = "REMOVE_TUTOR_FAILED";

export const REMOVE_STUDENT = "REMOVE_STUDENT";
export const REMOVE_STUDENT_SUCCEED = "REMOVE_STUDENT_SUCCEED";
export const REMOVE_STUDENT_FAILED = "REMOVE_STUDENT_FAILED";

export const REVIEW_TUTOR = "REVIEW_TUTOR";
export const REVIEW_TUTOR_SUCCEED = "REVIEW_TUTOR_SUCCEED";
export const REVIEW_TUTOR_FAILED = "REVIEW_TUTOR_FAILED";

export const GET_REVIEWS = "GET_REVIEWS";
export const GET_REVIEWS_SUCCEED = "GET_REVIEWS_SUCCEED";
export const GET_REVIEWS_FAILED = "GET_REVIEWS_FAILED";

export const SEARCH_SCHEDULE = "SEARCH_SCHEDULE";
export const SEARCH_SCHEDULE_SUCCEED = "SEARCH_SCHEDULE_SUCCEED";
export const SEARCH_SCHEDULE_FAILED = "SEARCH_SCHEDULE_FAILED";

export const UPLOAD_AVATAR = "UPLOAD_AVATAR";
export const UPLOAD_AVATAR_SUCCEED = "UPLOAD_AVATAR_SUCCEED";
export const UPLOAD_AVATAR_FAILED = "UPLOAD_AVATAR_FAILED";

export const FEEDBACK_SYSTEM = "FEEDBACK_SYSTEM";
export const FEEDBACK_SYSTEM_SUCCEED = "FEEDBACK_SYSTEM_SUCCEED";
export const FEEDBACK_SYSTEM_FAILED = "FEEDBACK_SYSTEM_FAILED";

export const GET_FEEDBACK = "GET_FEEDBACK";
export const GET_FEEDBACK_SUCCEED = "GET_FEEDBACK_SUCCEED";
export const GET_FEEDBACK_FAILED = "GET_FEEDBACK_FAILED";
