export const LOGIN_API = "LOGIN_API";
export const LOGIN_API_SUCCEED = "LOGIN_API_SUCCEED";
export const LOGIN_API_FAIL = "LOGIN_API_FAIL";
export const UPDATE_REMEMBERED_PATH = "UPDATE_REMEMBERED_PATH";
