export const LOGIN_API = "LOGIN_API";
export const LOGIN_API_SUCCEED = "LOGIN_API_SUCCEED";
export const LOGIN_API_FAIL = "LOGIN_API_FAIL";
export const UPDATE_REMEMBERED_PATH = "UPDATE_REMEMBERED_PATH";
export const CLOSE_MODAL_MESSAGE = "CLOSE_MODAL_MESSAGE";
export const OPEN_MODAL_MESSAGE = "OPEN_MODAL_MESSAGE";

