export const LOGIN_API = "LOGIN_API";
export const LOGIN_API_SUCCEED = "LOGIN_API_SUCCEED";
export const LOGIN_API_FAIL = "LOGIN_API_FAIL";

export const UPDATE_REMEMBERED_PATH = "UPDATE_REMEMBERED_PATH";
export const CLOSE_MODAL_MESSAGE = "CLOSE_MODAL_MESSAGE";
export const OPEN_MODAL_MESSAGE = "OPEN_MODAL_MESSAGE";

export const REGISTER_API = "REGISTER_API";
export const REGISTER_API_SUCCEED = "REGISTER_API_SUCCEED";
export const REGISTER_API_FAIL = "REGISTER_API_FAIL";

export const FORGOTPASSWORD_API = "FORGOTPASSWORD_API";
export const FORGOTPASSWORD_API_SUCCEED = "FORGOTPASSWORD_API_SUCCEED";
export const FORGOTPASSWORD_API_FAIL = "FORGOTPASSWORD_API_FAIL";

export const CONFIRMPASSWORD_API = "CONFIRMPASSWORD_API";
export const CONFIRMPASSWORD_API_SUCCEED = "CONFIRMPASSWORD_API_SUCCEED";
export const CONFIRMPASSWORD_API_FAIL = "CONFIRMPASSWORD_API_FAIL";

export const CHANGEPASSWORD_API = "CHANGEPASSWORD_API";
export const CHANGEPASSWORD_API_SUCCEED = "CHANGEPASSWORD_API_SUCCEED";
export const CHANGEPASSWORD_API_FAIL = "CHANGEPASSWORD_API_FAIL";

export const RESETPASSWORD_API = "RESETPASSWORD_API";
export const RESETPASSWORD_API_SUCCEED = "RESETPASSWORD_API_SUCCEED";
export const RESETPASSWORD_API_FAIL = "RESETPASSWORD_API_FAIL";

export const GET_SCHEDULE_API = "GET_SCHEDULE_API";
export const GET_SCHEDULE_API_SUCCEED = "GET_SCHEDULE_API_SUCCEED";
export const GET_SCHEDULE_API_FAIL = "GET_SCHEDULE_API_FAIL";

export const ADD_SCHEDULE_API = "ADD_SCHEDULE_API";
export const ADD_SCHEDULE_API_SUCCEED = "ADD_SCHEDULE_API_SUCCEED";
export const ADD_SCHEDULE_API_FAIL = "ADD_SCHEDULE_API_FAIL";

export const GET_TUTORINFO_API = "GET_TUTORINFO_API";
export const GET_TUTORINFO_API_SUCCEED = "GET_TUTORINFO_API_SUCCEED";
export const GET_TUTORINFO_API_FAIL = "GET_TUTORINFO_API_FAIL";
